package br.com.zup.shared

import io.micronaut.http.HttpStatus

enum class StatusConversion(
    val httpStatus: HttpStatus
) {
    OK(HttpStatus.OK),
    CANCELLED(HttpStatus.INTERNAL_SERVER_ERROR),
    UNKNOWN(HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_ARGUMENT(HttpStatus.BAD_REQUEST),
    DEADLINE_EXCEEDED(HttpStatus.REQUEST_TIMEOUT),
    NOT_FOUND(HttpStatus.NOT_FOUND),
    ALREADY_EXISTS(HttpStatus.BAD_REQUEST),
    PERMISSION_DENIED(HttpStatus.FORBIDDEN),
    RESOURCE_EXHAUSTED(HttpStatus.BAD_GATEWAY),
    FAILED_PRECONDITION(HttpStatus.PRECONDITION_FAILED),
    ABORTED(HttpStatus.INTERNAL_SERVER_ERROR),
    OUT_OF_RANGE(HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE),
    UNIMPLEMENTED(HttpStatus.NOT_IMPLEMENTED),
    INTERNAL(HttpStatus.INTERNAL_SERVER_ERROR),
    UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE),
    DATA_LOSS(HttpStatus.INTERNAL_SERVER_ERROR),
    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED);

}